# Getting started

In [1]:
import polars as pl
import datetime as dt
from pathlib import Path


path = Path.cwd() / "static" / "data.csv"
path.parent.mkdir(exist_ok=True)

## DataFrame operations

In [2]:
df = pl.DataFrame(
    {
        "name": ["Alice Archer", "Ben Brown", "Chloe Cooper", "Daniel Donovan"],
        "birthdate": [
            dt.date(1997, 1, 10),
            dt.date(1985, 2, 15),
            dt.date(1983, 3, 22),
            dt.date(1981, 4, 30),
        ],
        "weight": [57.9, 72.5, 53.6, 83.1],
        "height": [1.56, 1.77, 1.65, 1.75],
    }
)

df.write_csv(path)

df_csv = pl.read_csv(path, try_parse_dates=True)

## Selecting

In [3]:
df_selected = df.select(["name", "weight", "height", "birthdate"])

df_selected

shape: (4, 4)
┌────────────────┬────────┬────────┬────────────┐
│ name           ┆ weight ┆ height ┆ birthdate  │
│ ---            ┆ ---    ┆ ---    ┆ ---        │
│ str            ┆ f64    ┆ f64    ┆ date       │
╞════════════════╪════════╪════════╪════════════╡
│ Alice Archer   ┆ 57.9   ┆ 1.56   ┆ 1997-01-10 │
│ Ben Brown      ┆ 72.5   ┆ 1.77   ┆ 1985-02-15 │
│ Chloe Cooper   ┆ 53.6   ┆ 1.65   ┆ 1983-03-22 │
│ Daniel Donovan ┆ 83.1   ┆ 1.75   ┆ 1981-04-30 │
└────────────────┴────────┴────────┴────────────┘

## Mutating

In [4]:
df_mutated = df.with_columns(
    birth_year=pl.col("birthdate").dt.year(),
    bmi=(pl.col("weight") / pl.col("height") ** 2).round(1),
)

df_mutated

shape: (4, 6)
┌────────────────┬────────────┬────────┬────────┬────────────┬──────┐
│ name           ┆ birthdate  ┆ weight ┆ height ┆ birth_year ┆ bmi  │
│ ---            ┆ ---        ┆ ---    ┆ ---    ┆ ---        ┆ ---  │
│ str            ┆ date       ┆ f64    ┆ f64    ┆ i32        ┆ f64  │
╞════════════════╪════════════╪════════╪════════╪════════════╪══════╡
│ Alice Archer   ┆ 1997-01-10 ┆ 57.9   ┆ 1.56   ┆ 1997       ┆ 23.8 │
│ Ben Brown      ┆ 1985-02-15 ┆ 72.5   ┆ 1.77   ┆ 1985       ┆ 23.1 │
│ Chloe Cooper   ┆ 1983-03-22 ┆ 53.6   ┆ 1.65   ┆ 1983       ┆ 19.7 │
│ Daniel Donovan ┆ 1981-04-30 ┆ 83.1   ┆ 1.75   ┆ 1981       ┆ 27.1 │
└────────────────┴────────────┴────────┴────────┴────────────┴──────┘

## Filtering

In [5]:
df_filtered = df.filter(pl.col("birthdate").dt.month() == 3)

df_filtered

shape: (1, 4)
┌──────────────┬────────────┬────────┬────────┐
│ name         ┆ birthdate  ┆ weight ┆ height │
│ ---          ┆ ---        ┆ ---    ┆ ---    │
│ str          ┆ date       ┆ f64    ┆ f64    │
╞══════════════╪════════════╪════════╪════════╡
│ Chloe Cooper ┆ 1983-03-22 ┆ 53.6   ┆ 1.65   │
└──────────────┴────────────┴────────┴────────┘

## Grouping

In [6]:
df_grouped = df.group_by(decade=pl.col("birthdate").dt.year() // 10 * 10).agg(
    sample_size=pl.len(),
    average_weight=pl.col("weight").mean().round(2),
    tallest=pl.col("height").max(),
)

df_grouped

shape: (2, 4)
┌────────┬─────────────┬────────────────┬─────────┐
│ decade ┆ sample_size ┆ average_weight ┆ tallest │
│ ---    ┆ ---         ┆ ---            ┆ ---     │
│ i32    ┆ u32         ┆ f64            ┆ f64     │
╞════════╪═════════════╪════════════════╪═════════╡
│ 1990   ┆ 1           ┆ 57.9           ┆ 1.56    │
│ 1980   ┆ 3           ┆ 69.73          ┆ 1.77    │
└────────┴─────────────┴────────────────┴─────────┘

In [7]:
df_complex = (
    df.with_columns(
        (pl.col("birthdate").dt.year() // 10 * 10).alias("decade"),
        pl.col("name").str.split(by=" ").list.first(),
    )
    .select(
        pl.all().exclude("birthdate"),
    )
    .group_by(
        pl.col("decade"),
        maintain_order=True,
    )
    .agg(
        pl.col("name"),
        pl.col("weight", "height").mean().round(2).name.prefix("avg_"),
    )
)

df_complex

shape: (2, 4)
┌────────┬────────────────────────────┬────────────┬────────────┐
│ decade ┆ name                       ┆ avg_weight ┆ avg_height │
│ ---    ┆ ---                        ┆ ---        ┆ ---        │
│ i32    ┆ list[str]                  ┆ f64        ┆ f64        │
╞════════╪════════════════════════════╪════════════╪════════════╡
│ 1990   ┆ ["Alice"]                  ┆ 57.9       ┆ 1.56       │
│ 1980   ┆ ["Ben", "Chloe", "Daniel"] ┆ 69.73      ┆ 1.72       │
└────────┴────────────────────────────┴────────────┴────────────┘

## Combining

### Joining

In [8]:
df_new = pl.DataFrame(
    {
        "name": ["Ben Brown", "Daniel Donovan", "Alice Archer", "Chloe Cooper"],
        "parent": [True, False, False, False],
        "siblings": [1, 2, 3, 4],
    }
)

df_new

shape: (4, 3)
┌────────────────┬────────┬──────────┐
│ name           ┆ parent ┆ siblings │
│ ---            ┆ ---    ┆ ---      │
│ str            ┆ bool   ┆ i64      │
╞════════════════╪════════╪══════════╡
│ Ben Brown      ┆ true   ┆ 1        │
│ Daniel Donovan ┆ false  ┆ 2        │
│ Alice Archer   ┆ false  ┆ 3        │
│ Chloe Cooper   ┆ false  ┆ 4        │
└────────────────┴────────┴──────────┘

In [9]:
df.join(df_new, on="name", how="left")

shape: (4, 6)
┌────────────────┬────────────┬────────┬────────┬────────┬──────────┐
│ name           ┆ birthdate  ┆ weight ┆ height ┆ parent ┆ siblings │
│ ---            ┆ ---        ┆ ---    ┆ ---    ┆ ---    ┆ ---      │
│ str            ┆ date       ┆ f64    ┆ f64    ┆ bool   ┆ i64      │
╞════════════════╪════════════╪════════╪════════╪════════╪══════════╡
│ Alice Archer   ┆ 1997-01-10 ┆ 57.9   ┆ 1.56   ┆ false  ┆ 3        │
│ Ben Brown      ┆ 1985-02-15 ┆ 72.5   ┆ 1.77   ┆ true   ┆ 1        │
│ Chloe Cooper   ┆ 1983-03-22 ┆ 53.6   ┆ 1.65   ┆ false  ┆ 4        │
│ Daniel Donovan ┆ 1981-04-30 ┆ 83.1   ┆ 1.75   ┆ false  ┆ 2        │
└────────────────┴────────────┴────────┴────────┴────────┴──────────┘

### Concatenating

In [10]:
df_new = pl.DataFrame(
    {
        "name": ["Ethan Edwards", "Fiona Foster", "Grace Gibson", "Henry Harris"],
        "birthdate": [
            dt.date(1977, 5, 10),
            dt.date(1975, 6, 23),
            dt.date(1973, 7, 22),
            dt.date(1971, 8, 3),
        ],
        "weight": [67.9, 72.5, 57.6, 93.1],
        "height": [1.76, 1.6, 1.66, 1.8],
    }
)

df_new

shape: (4, 4)
┌───────────────┬────────────┬────────┬────────┐
│ name          ┆ birthdate  ┆ weight ┆ height │
│ ---           ┆ ---        ┆ ---    ┆ ---    │
│ str           ┆ date       ┆ f64    ┆ f64    │
╞═══════════════╪════════════╪════════╪════════╡
│ Ethan Edwards ┆ 1977-05-10 ┆ 67.9   ┆ 1.76   │
│ Fiona Foster  ┆ 1975-06-23 ┆ 72.5   ┆ 1.6    │
│ Grace Gibson  ┆ 1973-07-22 ┆ 57.6   ┆ 1.66   │
│ Henry Harris  ┆ 1971-08-03 ┆ 93.1   ┆ 1.8    │
└───────────────┴────────────┴────────┴────────┘

In [11]:
pl.concat([df, df_new], how="vertical")

shape: (8, 4)
┌────────────────┬────────────┬────────┬────────┐
│ name           ┆ birthdate  ┆ weight ┆ height │
│ ---            ┆ ---        ┆ ---    ┆ ---    │
│ str            ┆ date       ┆ f64    ┆ f64    │
╞════════════════╪════════════╪════════╪════════╡
│ Alice Archer   ┆ 1997-01-10 ┆ 57.9   ┆ 1.56   │
│ Ben Brown      ┆ 1985-02-15 ┆ 72.5   ┆ 1.77   │
│ Chloe Cooper   ┆ 1983-03-22 ┆ 53.6   ┆ 1.65   │
│ Daniel Donovan ┆ 1981-04-30 ┆ 83.1   ┆ 1.75   │
│ Ethan Edwards  ┆ 1977-05-10 ┆ 67.9   ┆ 1.76   │
│ Fiona Foster   ┆ 1975-06-23 ┆ 72.5   ┆ 1.6    │
│ Grace Gibson   ┆ 1973-07-22 ┆ 57.6   ┆ 1.66   │
│ Henry Harris   ┆ 1971-08-03 ┆ 93.1   ┆ 1.8    │
└────────────────┴────────────┴────────┴────────┘